# Base image
FROM --platform=linux/x86_64 amazon/aws-lambda-python:3.9

# Copy requirements file to wd
COPY . ${LAMBDA_TASK_ROOT}

# Install libraries
RUN pip install -r requirements.txt

# Command to run when running docker container
CMD ["main.lambda_handler"]