run_config:
  name: docker_demo
  author: Alejandra Lelo de Larrea Ibarra
  version: default
  desription: Predict whether an indvidual has a specific disease based on their medical measurements
  dependencies: requirements.txt
  output: results


load_data:
  url: "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
  columns:
    - pregnancies
    - glucose
    - blood_pressure
    - skin_thickness
    - insulin
    - bmi
    - diabetes_pedigree
    - age
    - outcome

prepare_data:
  target: outcome
  test_size: 0.3
  seed: 190322

training:
  param_grid:
    n_estimators: [100, 200, 300]
    max_features: ['auto', 'sqrt', 'log2']
    max_depth: [4, 6, 8, 10]
    criterion: ['gini', 'entropy']
  cv_k: 5
  seed: 190322

  