# Use an official Python runtime as a parent image


# Set the working directory in the container to /app


# Copy the current directory contents into the container's /app folder


# Install any needed packages specified in requirements.txt


# Run train_model.py when the container launches
